version: '3.8'

services:
  client:
    build:
      context: ./client
    environment:
      - VITE_API_URL=http://server:5000  # 👈 Use Docker service name for backend
    ports:
      - "5173:5173"
    # volumes:
    #   - ./client:/app
    depends_on:
      - server
    restart: unless-stopped

  server:
    build:
      context: ./server
    environment:
      - MONGO_URL=mongodb://mongo:27017/ecommerce
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    command: ["npm", "start"]
    restart: unless-stopped

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
